import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from '@/app/ui/sidenav';
import { courierPrime } from "./ui/fonts";
import "katex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: style scrollbar
  return (
    <html
      lang="en"
      className={`antialiased h-full overflow-clip`}
    >
      <body className={`h-full overflow-clip flex flex-col ${courierPrime.className}`}>
        <div className="h-full overflow-y-scroll md:scrollbar-auto scroll-smooth md:scroll-auto set-scroll-timeline-y set-view-timeline-y">
          <div className="h-180" />
          <div className="bg-black w-10 h-10 animate-bounce anim-timing-linrev [animation-timeline:view()] view-25%/75%" /> {/* [animation-timeline:view()] */}
          <div className="flex min-h-screen flex-col lg:flex-row lg:overflow-clip text-xl lg:text-lg">
            <SideNav />
            <div className="grow p-6 lg:overflow-y-auto lg:p-12">
              {children}
            </div>
            <div className="w-full flex-none lg:w-80 shrink-max"></div>
          </div>
        </div>
      </body>
    </html>
  );
}